plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
}

version = lib_version
group = lib_group

base {
    archivesName = "${lib_id}-neoforge-${minecraft_version}"
}

dependencies {
    implementation "net.neoforged:neoforge:${neoforge_version}"
    implementation "software.bernie.geckolib:${neoforge_geckolib}"
}

neoForge {
    version = neoforge_version

    runs {
        client { client() }
        server { server() }
    }

    mods {
        "${lib_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

processResources {
    var replaceProperties = [
        minecraft_version: minecraft_version,
        minecraft_version_range: minecraft_version_range,
        neoforge_version: neoforge_version,
        neoforge_version_range: neoforge_version_range,
        neoforge_loader_version_range: neoforge_loader_version_range,
        lib_id: lib_id,
        lib_name: lib_name,
        lib_license: lib_license,
        lib_version: lib_version,
        lib_authors: lib_authors,
        lib_description: lib_description,
        lib_homepage: lib_homepage,
        lib_source: lib_source,
        lib_issues: lib_issues
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml', 'pack.mcmeta']) {
        expand replaceProperties + [project: project]
    }

    filesMatching("${lib_id}.mixins.json") {
        expand([lib_id: lib_id])
    }
}

jar {
    from("../common/LICENSE") {
        rename { "${it}_${project.base.archivesName}" }
    }
    manifest {
        attributes([
            'Specification-Title': lib_id,
            'Specification-Vendor': lib_authors,
            'Specification-Version': '1',
            'Implementation-Title': project.name,
            'Implementation-Version': project.jar.archiveVersion,
            'Implementation-Vendor': lib_authors,
            'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}